steps:
- name: 'docker/compose:1.29.0'
  args:
  - "-f"
  - "docker/docker_compose/integration_test/docker-compose.yml"
  - "up"
  - "--build"
  - "--remove-orphans"
  - "--force-recreate"
  - "--abort-on-container-exit"
  - "--exit-code-from"
  - "test"