steps:
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/pathseeker:$SHORT_SHA'
  - '-f'
  - 'docker/pathseeker_app.dockerfile'
  - '.'

- name: 'docker/compose:1.19.0'
  args:
  - "-f"
  - "docker/docker_compose/integration_test/docker-compose.yml"
  - "up"
  - "--build"
  - "--remove-orphans"
  - "--force-recreate"
  - "--abort-on-container-exit"
  - "--exit-code-from"
  - "test"