version: '3.3'

services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ePXImvuAak3DqWOmJpqb
      MYSQL_DATABASE: pathseeker
      MYSQL_USER: W1AdlU0oUI8767S6f77N
      MYSQL_PASSWORD: q0UMFKTy5QVl5IhZieTr
    ports:
      - 3306:3306