version: '3.3'

services:
  dev_mysql_db:
    image: mysql
    container_name: dev_mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: "ePXImvuAak3DqWOmJpqb"
      MYSQL_DATABASE: "pathseeker"
      MYSQL_USER: "W1AdlU0oUI8767S6f77N"
      MYSQL_PASSWORD: "q0UMFKTy5QVl5IhZieTr"
    cap_add:
      - SYS_NICE
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
