version: '3.3'

services:
  dev_mysql_db:
    image: mysql
    container_name: dev_mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: "KttP98ZdZRbXTmgxjuVz6XrRt4H7BreU"
      MYSQL_DATABASE: "pathseeker"
      MYSQL_USER: "Gg6zGq5Ld8JG7jrxYYSz74abM285nqjf"
      MYSQL_PASSWORD: "ESqqUfg6xEreBMpmNn7qb3SqxBtsDUzJ"
    cap_add:
      - SYS_NICE
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
